apiVersion: v1
kind: Service
metadata:
  name: pelias-master
  labels:
    component: pelias
    role: master
spec:
  selector:
    component: pelias
    role: master
  ports:
  - name: transport
    port: 9300
    protocol: TCP
